### ISSUE TITLE
Discord image in README.md file should be a link

### ISSUE THREAD

**Issue by Holygent** [castdrian/CoreDex#4]
The README.md file contains an image that shows a Discord server. Currently, it's as follows:
`<img src="https://discord.com/api/guilds/1211664271243612251/widget.png?style=banner3" />`

If your repo has a Discord server, you should add a link to your image so people can join the server.

**Comment by castdrian** [comment]
the widget autogenerates the guild invite, but it would seem it requires the href to be set explicitly these days

**Comment by Holygent** [comment]
> the widget autogenerates the guild invite, but it would seem it requires the href to be set explicitly these days

Indeed it does, my apologies for the oversight.
